"""Tests for the NMEA 0183 GPS/GNSS sentence decoders.

Published example sentences carry their real checksums, so these tests exercise
the decoders against authoritative reference data rather than against
sentences generated by the code under test.
"""

from __future__ import annotations

import pytest

from aivdm.gps import (
    Gga,
    Gll,
    Gsa,
    Gsv,
    Hdg,
    Hdt,
    Rmc,
    Rot,
    Vtg,
    Zda,
    decode_sentence,
    fix_of,
)
from aivdm.nmea import parse_sentence


def nmea(body: str) -> str:
    """Build a sentence with an independently computed checksum."""
    value = 0
    for char in body:
        value ^= ord(char)
    return f"${body}*{value:02X}"


def decode(sentence: str) -> object:
    return decode_sentence(parse_sentence(sentence))


class TestGga:
    def test_published_example(self) -> None:
        parsed = parse_sentence("$GPGGA,123519,4807.038,N,01131.000,E,1,08,0.9,545.4,M,46.9,M,,*47")
        message = decode_sentence(parsed)
        assert isinstance(message, Gga)
        assert message.utc_time == "123519"
        assert message.latitude_deg == pytest.approx(48.1173)
        assert message.longitude_deg == pytest.approx(11.5166667)
        assert message.fix_quality == 1
        assert message.fix_quality_text == "GPS fix"
        assert message.satellites_used == 8
        assert message.hdop == pytest.approx(0.9)
        assert message.altitude_m == pytest.approx(545.4)
        assert message.geoid_separation_m == pytest.approx(46.9)
        assert message.dgps_age_s is None
        assert message.dgps_station_id is None

    def test_fix_quality_zero_suppresses_a_zero_filled_position(self) -> None:
        # The classic trap: receivers zero-fill an invalid fix, which would
        # otherwise decode as a real position in the Gulf of Guinea.
        message = decode(nmea("GPGGA,000000,0000.000,N,00000.000,E,0,00,,,M,,M,,"))
        assert isinstance(message, Gga)
        assert message.fix_quality == 0
        assert message.fix_quality_text == "fix not available"
        assert message.latitude_deg is None
        assert message.longitude_deg is None

    def test_empty_fields_are_none_not_zero(self) -> None:
        message = decode(nmea("GPGGA,,,,,,0,00,,,,,,"))
        assert isinstance(message, Gga)
        assert message.utc_time is None
        assert message.latitude_deg is None
        assert message.longitude_deg is None
        assert message.altitude_m is None
        assert message.hdop is None

    def test_dgps_fields(self) -> None:
        message = decode(nmea("GPGGA,123519,4807.038,N,01131.000,E,2,07,0.8,100.0,M,45.0,M,2.5,0123"))
        assert isinstance(message, Gga)
        assert message.fix_quality_text == "differential GPS fix"
        assert message.dgps_age_s == pytest.approx(2.5)
        assert message.dgps_station_id == "0123"

    def test_truncated_sentence_does_not_raise(self) -> None:
        message = decode("$GPGGA,123519")
        assert isinstance(message, Gga)
        assert message.latitude_deg is None

    def test_gnss_talker_decodes_identically(self) -> None:
        message = decode(nmea("GNGGA,123519,4807.038,N,01131.000,E,1,08,0.9,545.4,M,46.9,M,,"))
        assert isinstance(message, Gga)
        assert message.latitude_deg == pytest.approx(48.1173)


class TestRmc:
    def test_published_example(self) -> None:
        message = decode("$GPRMC,123519,A,4807.038,N,01131.000,E,022.4,084.4,230394,003.1,W*6A")
        assert isinstance(message, Rmc)
        assert message.utc_time == "123519"
        assert message.utc_date == "230394"
        assert message.status == "A"
        assert message.latitude_deg == pytest.approx(48.1173)
        assert message.longitude_deg == pytest.approx(11.5166667)
        assert message.sog_knots == pytest.approx(22.4)
        assert message.cog_deg == pytest.approx(84.4)
        assert message.magnetic_variation_deg == pytest.approx(-3.1)

    def test_west_variation_is_negative_and_east_positive(self) -> None:
        west = decode(nmea("GPRMC,123519,A,4807.038,N,01131.000,E,022.4,084.4,230394,003.1,W"))
        east = decode(nmea("GPRMC,123519,A,4807.038,N,01131.000,E,022.4,084.4,230394,003.1,E"))
        assert isinstance(west, Rmc) and isinstance(east, Rmc)
        assert west.magnetic_variation_deg == pytest.approx(-3.1)
        assert east.magnetic_variation_deg == pytest.approx(3.1)

    def test_missing_variation_indicator_is_none_not_negative(self) -> None:
        message = decode(nmea("GPRMC,123519,A,4807.038,N,01131.000,E,022.4,084.4,230394,003.1,"))
        assert isinstance(message, Rmc)
        assert message.magnetic_variation_deg is None

    def test_status_void_suppresses_position(self) -> None:
        message = decode(nmea("GPRMC,123519,V,4807.038,N,01131.000,E,022.4,084.4,230394,003.1,W"))
        assert isinstance(message, Rmc)
        assert message.status == "V"
        assert message.latitude_deg is None
        assert message.longitude_deg is None

    def test_nmea_23_mode_field(self) -> None:
        message = decode(nmea("GPRMC,123519,A,4807.038,N,01131.000,E,022.4,084.4,230394,003.1,W,A"))
        assert isinstance(message, Rmc)
        assert message.mode == "A"


class TestGll:
    def test_published_example(self) -> None:
        message = decode("$GPGLL,4916.45,N,12311.12,W,225444,A*31")
        assert isinstance(message, Gll)
        assert message.latitude_deg == pytest.approx(49.2741667)
        assert message.longitude_deg == pytest.approx(-123.1853333)
        assert message.utc_time == "225444"
        assert message.status == "A"

    def test_void_status_suppresses_position(self) -> None:
        message = decode(nmea("GPGLL,4916.45,N,12311.12,W,225444,V"))
        assert isinstance(message, Gll)
        assert message.latitude_deg is None


class TestVtg:
    def test_published_new_form(self) -> None:
        message = decode("$GPVTG,054.7,T,034.4,M,005.5,N,010.2,K*48")
        assert isinstance(message, Vtg)
        assert message.cog_true_deg == pytest.approx(54.7)
        assert message.cog_magnetic_deg == pytest.approx(34.4)
        assert message.sog_knots == pytest.approx(5.5)
        assert message.sog_kmh == pytest.approx(10.2)

    def test_legacy_form_without_unit_letters(self) -> None:
        message = decode(nmea("GPVTG,054.7,034.4,005.5,010.2"))
        assert isinstance(message, Vtg)
        assert message.cog_true_deg == pytest.approx(54.7)
        assert message.cog_magnetic_deg == pytest.approx(34.4)
        assert message.sog_knots == pytest.approx(5.5)
        assert message.sog_kmh == pytest.approx(10.2)

    def test_partially_empty_new_form(self) -> None:
        message = decode(nmea("GPVTG,054.7,T,,M,005.5,N,,K"))
        assert isinstance(message, Vtg)
        assert message.cog_magnetic_deg is None
        assert message.sog_kmh is None


class TestGsa:
    def test_published_example_skips_empty_prn_slots(self) -> None:
        message = decode("$GPGSA,A,3,04,05,,09,12,,,24,,,,,2.5,1.3,2.1*39")
        assert isinstance(message, Gsa)
        assert message.selection_mode == "A"
        assert message.fix_type == 3
        assert message.fix_type_text == "3D fix"
        assert message.active_prns == (4, 5, 9, 12, 24)
        assert message.pdop == pytest.approx(2.5)
        assert message.hdop == pytest.approx(1.3)
        assert message.vdop == pytest.approx(2.1)
        assert message.system_id is None

    def test_no_fix(self) -> None:
        message = decode(nmea("GPGSA,A,1,,,,,,,,,,,,,,,"))
        assert isinstance(message, Gsa)
        assert message.fix_type_text == "no fix"
        assert message.active_prns == ()

    def test_nmea_411_system_id(self) -> None:
        message = decode(nmea("GNGSA,A,3,04,05,,09,12,,,24,,,,,2.5,1.3,2.1,1"))
        assert isinstance(message, Gsa)
        assert message.system_id == "1"


class TestGsv:
    def test_published_example(self) -> None:
        message = decode("$GPGSV,3,1,11,03,03,111,00,04,15,270,00,06,01,010,00,13,06,292,00*74")
        assert isinstance(message, Gsv)
        assert message.messages_total == 3
        assert message.message_number == 1
        assert message.satellites_in_view == 11
        assert len(message.satellites) == 4
        assert message.satellites[0].prn == 3
        assert message.satellites[0].elevation_deg == pytest.approx(3)
        assert message.satellites[0].azimuth_deg == pytest.approx(111)
        assert message.satellites[0].snr_db == pytest.approx(0)
        assert message.satellites[3].prn == 13
        assert message.signal_id is None

    def test_trailing_signal_id_is_not_mistaken_for_a_satellite(self) -> None:
        message = decode(nmea("GPGSV,1,1,04,03,03,111,00,04,15,270,00,06,01,010,00,13,06,292,00,7"))
        assert isinstance(message, Gsv)
        assert message.signal_id == 7
        assert len(message.satellites) == 4
        assert [sat.prn for sat in message.satellites] == [3, 4, 6, 13]

    def test_untracked_satellite_has_null_snr(self) -> None:
        message = decode(nmea("GPGSV,1,1,01,03,03,111,"))
        assert isinstance(message, Gsv)
        assert message.satellites[0].snr_db is None

    def test_partial_trailing_quadruple_is_ignored(self) -> None:
        message = decode(nmea("GPGSV,1,1,02,03,03,111,00,04,15"))
        assert isinstance(message, Gsv)
        assert len(message.satellites) == 1


class TestZda:
    def test_published_example(self) -> None:
        message = decode("$GPZDA,201530.00,04,07,2002,00,00*60")
        assert isinstance(message, Zda)
        assert message.utc_time == "201530.00"
        assert message.utc_date == "2002-07-04"
        assert message.local_zone_hours == 0
        assert message.local_zone_minutes == 0

    def test_out_of_range_date_components_are_none(self) -> None:
        message = decode(nmea("GPZDA,201530.00,45,13,2002,00,00"))
        assert isinstance(message, Zda)
        assert message.utc_date is None


class TestHeadingAndRate:
    def test_hdt(self) -> None:
        message = decode(nmea("GPHDT,123.4,T"))
        assert isinstance(message, Hdt)
        assert message.heading_true_deg == pytest.approx(123.4)

    def test_hdg_signs_deviation_and_variation(self) -> None:
        message = decode(nmea("HCHDG,98.3,0.0,E,12.6,W"))
        assert isinstance(message, Hdg)
        assert message.heading_magnetic_deg == pytest.approx(98.3)
        assert message.deviation_deg == pytest.approx(0.0)
        assert message.variation_deg == pytest.approx(-12.6)

    def test_rot(self) -> None:
        message = decode(nmea("TIROT,12.3,A"))
        assert isinstance(message, Rot)
        assert message.rot_deg_per_min == pytest.approx(12.3)
        assert message.status == "A"


class TestCoordinateValidation:
    @pytest.mark.parametrize(
        ("lat", "hemisphere"),
        [
            ("4807.038", ""),  # missing indicator: must not default to North
            ("4807.038", "X"),
            ("", "N"),  # missing value
            ("not-a-number", "N"),
            ("4860.000", "N"),  # minutes >= 60 is malformed
            ("9900.000", "N"),  # degrees beyond the pole
            ("-4807.038", "N"),  # explicit signs are not permitted
        ],
    )
    def test_unusable_latitude_is_none(self, lat: str, hemisphere: str) -> None:
        message = decode(nmea(f"GPGGA,123519,{lat},{hemisphere},01131.000,E,1,08,0.9,545.4,M,46.9,M,,"))
        assert isinstance(message, Gga)
        assert message.latitude_deg is None

    def test_southern_and_western_are_negative(self) -> None:
        message = decode(nmea("GPGGA,123519,4807.038,S,01131.000,W,1,08,0.9,545.4,M,46.9,M,,"))
        assert isinstance(message, Gga)
        assert message.latitude_deg == pytest.approx(-48.1173)
        assert message.longitude_deg == pytest.approx(-11.5166667)

    def test_three_digit_longitude_degrees(self) -> None:
        message = decode(nmea("GPGGA,123519,0119.000,N,10651.2345,E,1,08,0.9,545.4,M,46.9,M,,"))
        assert isinstance(message, Gga)
        assert message.longitude_deg == pytest.approx(106.8539083)

    def test_longitude_beyond_180_is_rejected(self) -> None:
        message = decode(nmea("GPGGA,123519,4807.038,N,19031.000,E,1,08,0.9,545.4,M,46.9,M,,"))
        assert isinstance(message, Gga)
        assert message.longitude_deg is None


class TestDispatch:
    def test_unmodelled_formatter_returns_none(self) -> None:
        assert decode_sentence(parse_sentence(nmea("GPDTM,W84,C"))) is None
        assert decode_sentence(parse_sentence(nmea("INDPT,2.3,0.0"))) is None

    def test_ais_sentence_is_not_claimed_by_the_gps_decoder(self) -> None:
        assert decode_sentence(parse_sentence("!AIVDM,1,1,,A,3815GkhOib7a7O9t`1qqi`?H00gP,0*52")) is None


class TestFixOf:
    def test_extracts_from_gga_rmc_and_gll(self) -> None:
        for sentence in (
            "$GPGGA,123519,4807.038,N,01131.000,E,1,08,0.9,545.4,M,46.9,M,,*47",
            "$GPRMC,123519,A,4807.038,N,01131.000,E,022.4,084.4,230394,003.1,W*6A",
        ):
            message = decode_sentence(parse_sentence(sentence))
            assert message is not None
            fix = fix_of(message)
            assert fix is not None
            assert fix.latitude_deg == pytest.approx(48.1173)
            assert fix.longitude_deg == pytest.approx(11.5166667)

    def test_returns_none_without_a_position(self) -> None:
        message = decode_sentence(parse_sentence(nmea("GPGSV,1,1,00")))
        assert message is not None
        assert fix_of(message) is None

    def test_returns_none_for_a_void_fix(self) -> None:
        message = decode_sentence(parse_sentence(nmea("GPGGA,000000,0000.000,N,00000.000,E,0,00,,,M,,M,,")))
        assert message is not None
        assert fix_of(message) is None
