"""Tests for the per-message-type AIS payload decoders.

Every reference vector below is a real sentence whose checksum was verified
independently, and whose decoded fields were cross-checked against the pyais
implementation (see the oracle step in README). They are reference data, not
sentences generated by the code under test.

The few constructed payloads -- sentinel sweeps, truncated variants, and the
type 11 dispatch -- are marked as such. ``nmea_builder`` is a test-local
inverse of ``aivdm.bits``.
"""

from __future__ import annotations

import json
from dataclasses import asdict

import pytest
from nmea_builder import (
    base_station as base_station_fields,
)
from nmea_builder import (
    build,
    six,
)
from nmea_builder import (
    position_report as position_report_fields,
)

from aivdm.ais import FragmentAssembler, parse_aivdm
from aivdm.messages import (
    AtoNReport,
    BaseStationReport,
    ClassBPositionReport,
    ExtendedClassBReport,
    LongRangeReport,
    PositionReport,
    SarAircraftReport,
    StaticDataReportA,
    StaticDataReportB,
    StaticVoyageData,
    UnknownMessage,
    decode_payload,
)
from aivdm.nmea import parse_sentence

# --- reference vectors ------------------------------------------------------

REQUESTER_SAMPLE = "!AIVDM,1,1,,A,3815GkhOib7a7O9t`1qqi`?H00gP,0*52"
TYPE_1 = "!AIVDM,1,1,,A,13HOI:541swceR8Kqmr4lSkDP0gP,0*5E"
TYPE_4 = "!AIVDM,1,1,,A,403OviQvQGfN<rw02@HFpB100000,0*1E"
TYPE_5 = [
    "!AIVDM,2,1,0,A,55NPOOP2;H;s<HtKP00EHE:0@T4@Dl0000000016L961O5GfNNkQEp6ClRh0,0*71",
    "!AIVDM,2,2,0,A,00000000000,2*24",
]
TYPE_9 = "!AIVDM,1,1,,A,91b55wi;hbS4on`Avej1FCh0089h,0*68"
TYPE_18 = "!AIVDM,1,1,,A,B5NJ;PP0Emkw8`UJ;bv3U`g5SP06,0*53"
TYPE_19 = "!AIVDM,1,1,,A,C5N3SRP0=fCu28T:`Q`oPe3P62Pa0DNV:P@000000000J1p:2220,0*5D"
TYPE_21 = "!AIVDM,1,1,,A,E>kb5Qo37a2V0W2@87TW:000000@3AFL>de5000003sP0000000000000000,4*6B"
TYPE_24A = "!AIVDM,1,1,,A,H5NJ;PQ@E=B1HE=<Dh0000000000,0*0E"
TYPE_24B = "!AIVDM,1,1,,A,H5NJ;PU6123<30qG43ijkl3h<440,0*3A"
TYPE_24B_AUX = "!AIVDM,1,1,,A,H>eq`dDUHIJ40071EHi000Eq`f20,0*4C"
TYPE_27 = "!AIVDM,1,1,,A,K35E2bKm18PFbLbL,0*47"

ALL_VECTORS = [
    REQUESTER_SAMPLE,
    TYPE_1,
    TYPE_4,
    *TYPE_5,
    TYPE_9,
    TYPE_18,
    TYPE_19,
    TYPE_21,
    TYPE_24A,
    TYPE_24B,
    TYPE_24B_AUX,
    TYPE_27,
]


def decode(*sentences: str):
    """Run sentences through framing, reassembly and decoding."""
    assembler = FragmentAssembler()
    for sentence in sentences:
        assembled = assembler.push(parse_aivdm(parse_sentence(sentence)))
        if assembled is not None:
            return decode_payload(assembled.payload, assembled.fill_bits)
    raise AssertionError("no payload was assembled")


class TestVectorsAreWellFormed:
    @pytest.mark.parametrize("sentence", ALL_VECTORS)
    def test_checksum_verifies(self, sentence: str) -> None:
        assert parse_sentence(sentence).checksum_ok is True


class TestRequesterSample:
    """The message the requester supplied, asserted in full.

    Hand-decoded from the spec before any code existed; every value here also
    matches the independent pyais decode.
    """

    def test_full_decode(self) -> None:
        message = decode(REQUESTER_SAMPLE)
        assert isinstance(message, PositionReport)
        assert json.loads(json.dumps(asdict(message))) == {
            "message_type": 3,
            "repeat": 0,
            "mmsi": 538007503,
            "nav_status": 0,
            "nav_status_text": "Under way using engine",
            "rot_raw": 127,
            "rot_deg_per_min": None,
            # 127 is the saturation marker, not a measurement. Exposed so the
            # number a naive decoder reports stays reachable, without
            # pretending the field carries a magnitude.
            "rot_saturation_deg_per_min": 720.003211,
            "rot_text": "turning right at more than 5 deg/30 s (no turn indicator)",
            "sog_raw": 106,
            "sog_knots": 10.6,
            "position_accuracy": False,
            "lon_raw": 64109540,
            "lon_deg": 106.849233,
            "lat_raw": -3538457,
            "lat_deg": -5.897428,
            "cog_raw": 2502,
            "cog_deg": 250.2,
            "heading_deg": 263,
            "utc_second": 44,
            "utc_second_status": None,
            "maneuver": 0,
            "maneuver_text": "Not available",
            "raim": False,
            "radio_status": 3040,
        }

    def test_position_is_in_the_java_sea(self) -> None:
        message = decode(REQUESTER_SAMPLE)
        assert isinstance(message, PositionReport)
        assert message.lat_deg == pytest.approx(-5.9, abs=0.5)
        assert message.lon_deg == pytest.approx(106.85, abs=0.5)


class TestPositionReport:
    def test_type_1(self) -> None:
        message = decode(TYPE_1)
        assert isinstance(message, PositionReport)
        assert message.message_type == 1
        assert message.mmsi == 227006760
        assert message.nav_status == 5
        assert message.nav_status_text == "Moored"
        assert message.sog_knots == pytest.approx(12.3)
        assert message.cog_deg == pytest.approx(123.4)
        assert message.heading_deg == 121
        assert message.lon_deg == pytest.approx(-4.4321)
        assert message.lat_deg == pytest.approx(48.7654)
        assert message.utc_second == 42
        assert message.position_accuracy is True
        assert message.maneuver_text == "No special maneuver"

    def test_all_sentinels_decode_to_none(self) -> None:
        payload, fill_bits = build(
            position_report_fields(
                mmsi=123456789,
                nav_status=15,
                rot=-128,  # no turn information
                sog=1023,  # SOG not available
                lon=181 * 600_000,  # longitude not available
                lat=91 * 600_000,  # latitude not available
                cog=3600,  # COG not available
                heading=511,  # heading not available
                second=60,  # timestamp not available
            )
        )
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, PositionReport)
        assert message.nav_status == 15
        assert message.nav_status_text == "Undefined"
        assert message.rot_raw == -128
        assert message.rot_deg_per_min is None
        assert message.rot_saturation_deg_per_min is None
        assert message.rot_text == "no turn information available"
        assert message.sog_raw == 1023
        assert message.sog_knots is None
        assert message.lon_deg is None
        assert message.lat_deg is None
        assert message.cog_deg is None
        assert message.heading_deg is None
        assert message.utc_second is None
        assert message.utc_second_status == "not available"

    @pytest.mark.parametrize(
        ("raw", "expected"),
        [
            (60, "not available"),
            (61, "manual input mode"),
            (62, "estimated (dead reckoning) mode"),
            (63, "positioning system inoperative"),
        ],
    )
    def test_second_special_values(self, raw: int, expected: str) -> None:
        payload, fill_bits = build(position_report_fields(second=raw))
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, PositionReport)
        assert message.utc_second is None
        assert message.utc_second_status == expected

    def test_sog_at_max_reports_the_floor(self) -> None:
        payload, fill_bits = build(position_report_fields(sog=1022))
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, PositionReport)
        # 1022 means "102.2 knots or more"; sog_raw is the escape hatch.
        assert message.sog_raw == 1022
        assert message.sog_knots == 102.2

    @pytest.mark.parametrize("raw", [1, 20, 126])
    def test_rot_formula_matches_the_spec(self, raw: int) -> None:
        payload, fill_bits = build(position_report_fields(rot=raw))
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, PositionReport)
        # ROT_AIS = 4.733 * sqrt(ROT_sensor), so decode by dividing and squaring.
        assert message.rot_deg_per_min == pytest.approx(round((raw / 4.733) ** 2, 6))
        assert message.rot_saturation_deg_per_min is None
        assert message.rot_text is None

    def test_negative_rot_is_port(self) -> None:
        payload, fill_bits = build(position_report_fields(rot=-20))
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, PositionReport)
        assert message.rot_raw == -20
        assert message.rot_deg_per_min == pytest.approx(-round((20 / 4.733) ** 2, 6))
        assert message.rot_text is None

    def test_raw_one_is_not_confused_with_not_turning(self) -> None:
        # (1/4.733)**2 == 0.044640288. Rounding to one decimal would collapse
        # this to 0.0, which reads as "not turning" — a different statement.
        payload, fill_bits = build(position_report_fields(rot=1))
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, PositionReport)
        assert message.rot_deg_per_min == pytest.approx(0.04464, abs=1e-9)
        assert message.rot_deg_per_min != 0.0

    @pytest.mark.parametrize("raw", [127, -127])
    def test_turning_sentinels_carry_no_magnitude_but_expose_the_saturation(
        self, raw: int
    ) -> None:
        """Pins the deliberate divergence from decoders that skip the sentinel check.

        aggsoft (and any decoder that applies the formula blindly) reports
        ``(127 / 4.733) ** 2 == 720.003210529537`` for raw 127. That is where the
        *encoding* saturates, not a measured rate: the spec defines 127 as
        "turning, no turn indicator available", and 1..126 already covers up to
        708.709. The magnitude therefore stays null and the bound is reported
        separately.
        """
        payload, fill_bits = build(position_report_fields(rot=raw))
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, PositionReport)
        assert message.rot_raw == raw
        assert message.rot_deg_per_min is None
        assert message.rot_saturation_deg_per_min == pytest.approx(720.003211)
        assert message.rot_text is not None
        assert message.rot_text.startswith("turning right" if raw > 0 else "turning left")

    def test_the_encoding_really_does_saturate_at_127(self) -> None:
        # Guards the arithmetic behind rot_saturation_deg_per_min.
        payload, fill_bits = build(position_report_fields(rot=126))
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, PositionReport)
        assert message.rot_deg_per_min == pytest.approx(708.709218)
        assert message.rot_saturation_deg_per_min is None


class TestBaseStationReport:
    def test_type_4(self) -> None:
        message = decode(TYPE_4)
        assert isinstance(message, BaseStationReport)
        assert message.message_type == 4
        assert message.mmsi == 3669702
        assert message.year == 2024
        assert message.month == 5
        assert message.day == 15
        assert message.hour == 14
        assert message.minute == 30
        assert message.second == 12
        assert message.lon_deg == pytest.approx(-70.1234)
        assert message.lat_deg == pytest.approx(42.5678)
        assert message.epfd_text == "GPS"

    def test_type_11_dispatches_to_the_base_station_decoder(self) -> None:
        # Constructed rather than oracle-generated: pyais cannot emit a type 11
        # sentence -- encode_dict({"type": 11, ...}) silently produces type 4
        # bits, so this dispatch path is untested by the cross-check. Types 4
        # and 11 share a layout, so the field values themselves are covered by
        # the type 4 vector above; what is asserted here is the dispatch.
        payload, fill_bits = build(
            base_station_fields(
                message_type=11,
                mmsi=3669701,
                year=2024,
                month=9,
                day=17,
                hour=6,
                minute=5,
                second=4,
                lon=64109520,
                lat=-3538440,
                epfd=7,  # Surveyed
                raim=1,
            )
        )
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, BaseStationReport)
        assert message.message_type == 11
        assert message.mmsi == 3669701
        assert message.year == 2024
        assert message.month == 9
        assert message.day == 17
        assert message.hour == 6
        assert message.minute == 5
        assert message.second == 4
        assert message.lon_deg == pytest.approx(106.8492)
        assert message.lat_deg == pytest.approx(-5.8974)
        assert message.epfd_text == "Surveyed"
        assert message.raim is True

    def test_sentinel_date_components_are_none(self) -> None:
        payload, fill_bits = build(
            [
                (4, 6),
                (0, 2),
                (1, 30),
                (0, 14),
                (0, 4),
                (0, 5),
                (24, 5),
                (60, 6),
                (60, 6),
                (0, 1),
                (181 * 600_000, 28),
                (91 * 600_000, 27),
                (0, 4),
                (0, 10),
                (0, 1),
                (0, 19),
            ]
        )
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, BaseStationReport)
        assert message.year is None
        assert message.month is None
        assert message.day is None
        assert message.hour is None
        assert message.minute is None
        assert message.second is None
        assert message.lon_deg is None
        assert message.lat_deg is None


class TestStaticVoyageData:
    def test_type_5_two_fragment(self) -> None:
        message = decode(*TYPE_5)
        assert isinstance(message, StaticVoyageData)
        assert message.message_type == 5
        assert message.mmsi == 367533950
        assert message.imo_number == 9134270
        assert message.call_sign == "3FOF8"
        assert message.name == "EVER DIADEM"
        assert message.ship_type == 70
        assert message.ship_type_text == "Cargo, all ships of this type"
        assert message.destination == "NEW YORK"
        assert message.draught_m == pytest.approx(12.3)
        assert message.dimensions.bow == 225
        assert message.dimensions.stern == 70
        assert message.dimensions.port == 1
        assert message.dimensions.starboard == 31
        assert message.epfd_text == "GPS"
        assert message.eta.month == 5
        assert message.eta.day == 15
        assert message.eta.hour == 14
        assert message.eta.minute == 30
        assert message.dte is False

    def test_truncated_420_bit_variant_still_yields_the_identity(self) -> None:
        # Type 5 turns up at 420/422/426 bits in the wild. At 420 the destination
        # tail is lost, but every identity field -- which is what the requester
        # actually asked for -- survives intact.
        full, _ = build(
            [
                (5, 6),
                (0, 2),
                (367533950, 30),
                (0, 2),  # AIS version
                (9134270, 30),  # IMO number
                *six("3FOF8", 7),
                *six("EVER DIADEM", 20),
                (70, 8),  # ship type
                (225, 9),  # dim to bow
                (70, 9),  # dim to stern
                (1, 6),
                (31, 6),
                (1, 4),  # EPFD
                (5, 4),  # ETA month
                (15, 5),  # ETA day
                (14, 5),  # ETA hour
                (30, 6),  # ETA minute
                (123, 8),  # draught, tenths of a metre
                *six("NEW YORK", 20),
                (0, 1),  # DTE
                (0, 1),  # spare
            ]
        )
        assert len(full) == 71  # 426 armored bits, 2 of them fill -> 424

        message = decode_payload(full[:70], 0)  # exactly 420 bits
        assert isinstance(message, StaticVoyageData)
        assert message.name == "EVER DIADEM"
        assert message.call_sign == "3FOF8"
        assert message.imo_number == 9134270
        assert message.ship_type == 70
        assert message.dimensions.bow == 225
        assert message.draught_m == pytest.approx(12.3)
        assert message.eta.month == 5
        # Only the tail is lost.
        assert message.destination == ""
        assert message.dte is None

    def test_empty_text_fields_are_empty_strings(self) -> None:
        full, _ = build(
            [
                (5, 6),
                (0, 2),
                (1, 30),
                (0, 2),
                (0, 30),
                *six("", 7),
                *six("", 20),
                (0, 8),
                (0, 9),
                (0, 9),
                (0, 6),
                (0, 6),
                (0, 4),
                (0, 4),
                (0, 5),
                (0, 5),
                (0, 6),
                (0, 8),
                *six("", 20),
                (0, 1),
                (0, 1),
            ]
        )
        message = decode_payload(full, 0)
        assert isinstance(message, StaticVoyageData)
        assert message.name == ""
        assert message.call_sign == ""
        assert message.destination == ""
        assert message.dimensions.bow is None
        assert message.dimensions.starboard is None
        assert message.eta.month is None
        assert message.dte is False


class TestSarAircraftReport:
    def test_type_9(self) -> None:
        message = decode(TYPE_9)
        assert isinstance(message, SarAircraftReport)
        assert message.mmsi == 111232511
        assert message.altitude_m == 303
        assert message.sog_knots == pytest.approx(42)
        assert message.cog_deg == pytest.approx(34.5)
        assert message.lon_deg == pytest.approx(43.0075)
        assert message.lat_deg == pytest.approx(31.4222)
        assert message.utc_second == 15
        assert message.dte is False


class TestClassB:
    def test_type_18(self) -> None:
        message = decode(TYPE_18)
        assert isinstance(message, ClassBPositionReport)
        assert message.mmsi == 367430530
        assert message.sog_knots == pytest.approx(8.7)
        assert message.cog_deg == pytest.approx(210.5)
        assert message.heading_deg == 209
        assert message.lon_deg == pytest.approx(-122.345678)
        assert message.lat_deg == pytest.approx(37.812345)
        assert message.cs_unit is True
        assert message.has_display is False
        assert message.has_dsc is True
        assert message.can_use_all_bands is True
        assert message.accepts_message_22 is False

    def test_type_19_carries_name_and_dimensions(self) -> None:
        message = decode(TYPE_19)
        assert isinstance(message, ExtendedClassBReport)
        assert message.mmsi == 367059850
        assert message.name == "CAPT JOSEPH"
        assert message.ship_type == 52
        assert message.ship_type_text == "Tug"
        assert message.dimensions.bow == 30
        assert message.dimensions.stern == 20
        assert message.cog_deg == pytest.approx(88.8)
        assert message.heading_deg == 90

    def test_type_18_has_no_name_field(self) -> None:
        assert not hasattr(decode(TYPE_18), "name")


class TestAtoNReport:
    def test_type_21(self) -> None:
        message = decode(TYPE_21)
        assert isinstance(message, AtoNReport)
        assert message.mmsi == 993691015
        assert message.aton_type == 14
        assert message.aton_type_text == "Beacon, starboard hand"
        assert message.name == "FORELAND POINT"
        assert message.lon_deg == pytest.approx(1.429167)
        assert message.lat_deg == pytest.approx(51.375)
        assert message.off_position is False
        assert message.virtual_aid is False
        assert message.epfd_text == "Surveyed"

    def test_dimensions_of_zero_are_not_available(self) -> None:
        # AIS uses 0 for "not available"; an AtoN is not zero metres wide.
        message = decode(TYPE_21)
        assert isinstance(message, AtoNReport)
        assert message.dimensions.bow is None
        assert message.dimensions.starboard is None

    def test_name_extension_is_captured(self) -> None:
        long_name = "FORELAND POINT LIGHT"
        assert len(long_name) == 20  # fills the field, so no '@' padding

        payload, fill_bits = build(
            [
                (21, 6),
                (0, 2),
                (993691015, 30),
                (14, 5),  # aid type
                *six(long_name, 20),
                (1, 1),  # position accuracy
                (0, 28),
                (0, 27),
                (0, 9),
                (0, 9),
                (0, 6),
                (0, 6),
                (7, 4),  # EPFD
                (55, 6),  # UTC second
                (0, 1),  # off position
                (0, 8),  # regional reserved
                (0, 1),  # RAIM
                (0, 1),  # virtual aid
                (0, 1),  # assigned
                (0, 1),  # spare
                *six(" LIGHT", 6),  # name extension, bits 272+
            ]
        )
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, AtoNReport)
        assert message.name == long_name
        assert message.name_extension == " LIGHT"

    def test_short_name_needs_no_extension(self) -> None:
        payload, fill_bits = build(
            [
                (21, 6),
                (0, 2),
                (993691015, 30),
                (14, 5),
                *six("SHORT", 20),
                (1, 1),
                (0, 28),
                (0, 27),
                (0, 9),
                (0, 9),
                (0, 6),
                (0, 6),
                (7, 4),
                (55, 6),
                (0, 1),
                (0, 8),
                (0, 1),
                (0, 1),
                (0, 1),
                (0, 1),
            ]
        )
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, AtoNReport)
        assert message.name == "SHORT"
        assert message.name_extension == ""


class TestStaticDataReport:
    def test_part_a_carries_the_name(self) -> None:
        message = decode(TYPE_24A)
        assert isinstance(message, StaticDataReportA)
        assert message.part_number == 0
        assert message.mmsi == 367430530
        assert message.name == "TEST VESSEL"

    def test_part_b_carries_identity_and_dimensions(self) -> None:
        message = decode(TYPE_24B)
        assert isinstance(message, StaticDataReportB)
        assert message.part_number == 1
        assert message.ship_type == 70
        assert message.ship_type_text == "Cargo, all ships of this type"
        assert message.vendor_id == "ABC"
        assert message.unit_model == 3
        assert message.serial_number == 12345
        assert message.call_sign == "WDC1234"
        assert message.dimensions is not None
        assert message.dimensions.bow == 30
        assert message.dimensions.starboard == 4
        assert message.mothership_mmsi is None

    def test_auxiliary_craft_tail_is_a_mothership_mmsi(self) -> None:
        message = decode(TYPE_24B_AUX)
        assert isinstance(message, StaticDataReportB)
        assert message.mmsi == 987654321
        # "98" prefix: the 30-bit tail is a parent ship, not dimensions.
        assert message.dimensions is None
        assert message.mothership_mmsi == 367430530
        assert message.call_sign == "AUX1"

    def test_forbidden_part_numbers_degrade_to_unknown(self) -> None:
        payload, fill_bits = build([(24, 6), (0, 2), (1, 30), (2, 2)])
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, UnknownMessage)
        assert message.message_type == 24


class TestLongRangeReport:
    def test_type_27(self) -> None:
        message = decode(TYPE_27)
        assert isinstance(message, LongRangeReport)
        assert message.mmsi == 206914217
        assert message.sog_knots == pytest.approx(57)
        assert message.cog_deg == pytest.approx(167)
        assert message.lon_deg == pytest.approx(137.016667, abs=0.01)
        assert message.lat_deg == pytest.approx(4.833333, abs=0.01)
        assert message.nav_status is not None
        assert message.gnss_position is False

    def test_out_of_range_coordinates_are_rejected(self) -> None:
        # The 181/91 degree sentinels land outside the valid range whatever
        # encoding the spec means, so the range check doubles as the sentinel
        # check and the ambiguity never reaches the output.
        payload, fill_bits = build(
            [
                (27, 6),
                (0, 2),
                (1, 30),
                (0, 1),
                (0, 1),
                (0, 4),
                (181 * 600, 18),
                (91 * 600, 17),
                (63, 6),
                (511, 9),
                (0, 1),
                (0, 1),
            ]
        )
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, LongRangeReport)
        assert message.lon_deg is None
        assert message.lat_deg is None
        assert message.sog_knots is None
        assert message.cog_deg is None


class TestDegenerateInput:
    def test_unknown_message_type_is_preserved(self) -> None:
        payload, fill_bits = build([(28, 6), (0, 2), (123456789, 30), (0, 8)])
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, UnknownMessage)
        assert message.message_type == 28
        assert message.mmsi == 123456789
        assert message.payload == payload

    def test_truncated_payload_degrades_to_unknown_not_an_exception(self) -> None:
        payload, fill_bits = build([(5, 6), (0, 2), (1, 30)])
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, UnknownMessage)
        assert message.message_type == 5

    def test_five_bit_payload_yields_an_unknown_with_no_mmsi(self) -> None:
        payload, fill_bits = build([(1, 6)], total_bits=5)
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, UnknownMessage)
        assert message.mmsi is None

    def test_bit_length_reflects_fill_bits(self) -> None:
        unknown = decode_payload("0", 0)
        assert isinstance(unknown, UnknownMessage)
        assert unknown.bit_length == 6

        trimmed = decode_payload("0", 2)
        assert isinstance(trimmed, UnknownMessage)
        assert trimmed.bit_length == 4

    def test_payload_shorter_than_the_type_field_is_reported_as_type_zero(self) -> None:
        payload, fill_bits = build([(1, 6)], total_bits=5)
        message = decode_payload(payload, fill_bits)
        assert isinstance(message, UnknownMessage)
        # 0 is not a valid AIS message type, so it cannot be mistaken for one.
        assert message.message_type == 0
        assert message.repeat is None
        assert message.mmsi is None
